library(ggplot2)
setwd("./Desktop/FollowerCountHistory")
data <- read.csv("megynkelly-last.csv")
dates <- as.POSIXct(data$date, format="%Y-%m-%d")
#dates = as.character(data$date)
min_date <- min(dates$%Y)
max_date <- max(dates)
test <- as.numeric(min_date)
min_count <- min(data$count)
max_count <- max(data$count)
mar.default <- c(5,2,4,2) + 0.01
par(mar = mar.default + c(0, 4, 0, 0)) 
unixdata <- data.frame(date=as.numeric(as.POSIXct(data$date)), count=data$count)
plot(unixdata, type="o", col="red", ylim=c(min_count,max_count), xlim=c(min(unixdata$date),max(unixdata$date)), axes=FALSE, ann=FALSE) #, xlim=c(as.numeric(min_date),as.numeric(max_date))
box()
title(main="Megyn Kelly Follower Count over Time", col.main="red", font.main=4)
# Label the x and y axes with dark green text
#title(xlab="Dates", col.lab=rgb(0,0.5,0))
#title(ylab="Follower Count", col.lab=rgb(0,0.5,0))
#axis.Date(1, at=seq(min(dates), max(dates), "6 mon"), labels = FALSE)
axis(1, las=1, at=seq(min_date, max_date, "12 mon"), labels = substring(seq(min_date, max_date, "12 mon"), 1,4))
#axis(1, at=dates[1:70], labels = FALSE)
#axis(1, las=2, at=data$date[seq(1,70,6)], labels = dates[seq(1,70,6)])
axis(2, las=1, at=seq(0,max_count+199999,200000), labels=prettyNum(seq(0,max_count+199999,200000),big.mark=",",scientific=FALSE))